# Generated by Django 3.0.3 on 2020-05-13 13:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_auto_20200430_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('banner_image', models.ImageField(upload_to='')),
                ('description', tinymce.models.HTMLField()),
                ('categories', models.ManyToManyField(to='locations.Type')),
            ],
        ),
    ]
