# Generated by Django 3.0.3 on 2020-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
