# Generated by Django 3.0.3 on 2020-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_category', '0002_auto_20200514_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
