# Generated by Django 3.0.3 on 2020-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200422_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='suburb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
