# Generated by Django 3.0.3 on 2020-04-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
